version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3035:3000'
    environment:
      NODE_ENV: production
      BLOCKSTREAM_CLIENT_ID: ${BLOCKSTREAM_CLIENT_ID}
      BLOCKSTREAM_CLIENT_SECRET: ${BLOCKSTREAM_CLIENT_SECRET}
    networks:
      - web

networks:
  web:
    external: true